#!/bin/bash

function homescreen() {
    laptop_screen=$('xrandr | egrep 'e?DP-?[0-9]*' -o | head -n 1');
    xrandr;
    sleep 1;
    xrandr --output HDMI-0 --auto --primary;
    xrandr --output $laptop_screen --off
}

homescreen
